### ISSUE TITLE
Error on compiling Android Pie 

### ISSUE THREAD

**Issue by amsurana** [technexion-android/manifest#2]
I downloaded the branch `tn-p9.0.0_2.2.0-ga`
But looks like some projects are missing. Please support. 

I am compiling for imx7 pico. There is no folder `vendor/nxp/qca-wifi-bt` in the sources.
Your support is appreciated.

ninja: error: 'vendor/nxp/qca-wifi-bt/qca_proprietary/Android_HAL/wcnss_filter_8mq', needed by 'out/target/product/pico_imx7/vendor/bin/wcnss_filter', missing and no known rule to make it

**Comment by amsurana** [comment]
Solution: read file cookers/README.md for downloading proprietary files!

**Comment by wigcheng** [comment]
yes you did it, note that the tn-p9.0.0_2.2.0-ga branch is not ready yet, so many functions also not verified, we will be released soon.
